server:
  port: 7001
eureka:
  instance:
    hostname: localhost
#    ip-address: 192.168.200.100
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
