server:
  port: 9002
sa-token:
  token-name: csusertoken
  timeout: 86400
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true
spring:
  application:
    name: cs-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.75.66.14:3307/cscustomer?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: molin
    password: cmlwxt1231
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
